# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 245d77849ad560bd34528a40a07915fdda07c989709cabaafd8b5c9bc19c8a1afaef40369af9e75a3bacc2794930669678768e24bd490325ebb340d4903cc5ee

test:
  secret_key_base: e27e80d8bda5db26a8ebe77c9758bdc5000c042670a865b7837563862b92cec6b95e736780ac5cf672387e6f145c3fc5d3b3d5767f7219d71f1a872a18adf4a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
